release: 1.1.0
zabbix_version: "7.0"

managed:
  templates:
    - Provider
    - EcoFlow Station by API
    - Mikrotik by SNMP

  items: true
  triggers: true
  valueMaps: true
  graphs: true
  mediaTypes: true
  templateDashboards: true
  triggerActions:
    - "EcoFlow Сповіщення: Заряд 90%"
    - "EcoFlow Сповіщення: Заряд 33%"
    - "EcoFlow Сповіщення: Критичний заряд 15%"
    - "Інтернет сповіщення: Основне (оптика On/Off)"
    - "EcoFlow Генератор: Старт 15 спроб"
    - "EcoFlow Генератор: Стоп 15 спроб"

protected:
  hosts: true
  hostMacros: true
  interfaces: true
  history: true
  trends: true
  events: true
  problems: true